### ISSUE TITLE
1.20 checklist

### ISSUE THREAD

**Issue by SirEdvin** [SirEdvin/UnlimitedPeripheralWorks#18]
- [x] Robust peripheral proxy testing
  - [x] Peripheral proxy via peripheral proxy
  - [x] Incorrect handling for many `_` in peripheral name (should be ported to 1.19.4 also)
